language:
- ruby
rvm:
- 2.3.3
services: 
- postgresql
before_script:
- psql -c 'create database wombat_wonders_test;' -U postgres
before_install:
- sudo apt-get install -y postgresql-server-dev-9.2
script:
- bin/rails db:reset
- bin/rails db:migrate
- bundle exec rspec spec
after_script:
- bundle exec rake coveralls:push
- rake db:migrate
branches:
  only: 
  - master